### ISSUE TITLE
still getting issues on serialport - RPi 4

### ISSUE THREAD

**Issue by ubidefeo** [WebReflection/archibold.io#14]
@WebReflection 
I still get serialport bindings issues.

I'll upgrade Node and fix it (already been there) but maybe it's something you want to look into :)

```
> electron . --no-sandbox --disable-frame-rate-limit

App threw an error during load
Error: The module '/home/alarm/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/home/alarm/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:1
```

**Comment by WebReflection** [comment]
they updated all modules, so maybe I should drop the LTS version and use NodeJS 13 instead ... but I won't have time soon

**Comment by ubidefeo** [comment]
no worries, just notifying.
actually I ended up doing
`[~/] npm i electron-rebuild` 
`[~/] npm i serialport --arch=armv7l` 
`[~/] npm rebuild` 
`[~/] electron-rebuild` 

in case someone ends up having the same issue it's good to know :)
